utils::globalVariables(c('unitGroup', ':::', 'Selected',
                         'sd',
                         'value',
                         'UnitGroup',
                         'Perc_Matches',
                         'matchN',
                         'value',
                         'unitID',
                         'V1',
                         'V2',
                         'unitID',
                         'InclusionProb',
                         'calipers',
                         'selectedunitIDx',
                         'sub_units',
                         'key',
                         'sd',
                         'unitGroup',
                         'value',
                         'SMD',
                         'Covariate'))

